name: Test and SOnarcloud Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.4
      - name: dotnet restore
        run: dotnet restore
        
      - name: Dotnet build
        run: dotnet build
        
      - name: dotnet test
        run: dotnet-test

